### Send request with dynamic variables in request's body
POST http://localhost:8888/boardPost/registrationPost
Content-Type: application/json

{
  "postId": "78a6abf5-3014-4545-a113-82574fe2fcac",
  "title": "title",
  "contents": "contents",
  "writer": "writer",
  "password": "password"
}

