### 게시물 등록
POST http://localhost:8888/board/registBoard
Content-Type: application/json

{
  "title": "Axon프레임워크 구성",
  "contents": "안녕하세요.",
  "writer": "오준석",
  "password": "123456789ABCDEFG"
}

### 게시물 수정
POST http://localhost:8888/board/editBoard
Content-Type: application/json


{
  "boardId": "3ae7684c-db3d-4611-85b2-ae8abe9eb934",
  "title": "AxonFramewo3drk 구성(수정)",
  "contents": "반갑습니다.",
  "writer": "연구개발팀장",
  "password": "ABCDEF234456789"
}

### 등록된 게시물 이벤트 히스토리 조회
GET http://localhost:8888/board/{{boardId}}/events
Content-Type: application/json

### 등록된 게시물 조회
GET http://localhost:8888/board/{{boardId}}/xml
Content-Type: application/json

### 등록된 게시물 조회
GET http://localhost:8888/board/{{boardId}}/annotation
Content-Type: application/json
