### 게시물 등록
POST http://localhost:8888/board/registBoard
Content-Type: application/json

{
  "title": "Axon프레임워크 구성",
  "contents": "자료가 턱 없이 부족하고 거의 대부분이 영문 자료 뿐이다..",
  "writer": "오준석",
  "password": "123456789ABCDEFG"
}

### 게시물 수정
POST http://localhost:8888/board/editBoard
Content-Type: application/json


{
  "boardId": "e0efc6a5-dbc8-4064-9477-19c198c66495",
  "title": "AxonFramework 구성(수정)",
  "contents": "조금씩 조금씩 하나씩 시간이 부족하군..",
  "writer": "연구개발팀장",
  "password": "ABCDEFG123456789"
}

### 등록된 게시물 이벤트 히스토리 조회
GET http://localhost:8888/board/{{boardId}}/events
Content-Type: application/json

### 등록된 게시물 조회
GET http://localhost:8888/board/{{boardId}}/list
Content-Type: application/json

### 등록된 게시물 조회
GET http://localhost:8888/board/{{boardId}}/annolist
Content-Type: application/json
